[project]
name = "Artifact-Selector"
version = "1.0.0"
authors = [{ name = "Mad Dog Fist" }]
description = "Press a key to switch Artifacts."

[tool.sdkmod]
name = "Artifact Selector"
mod_type = "Standard" # or "Library"
supported_games = ["BL1"]
coop_support = "Unknown"
download = "https://github.com/maddogfist/Maddogfist-BL1-SDK-Mods/raw/refs/heads/main/ArtifactSelector/ArtifactSelector.sdkmod"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }