[project]
name = "SLAB Qol"
version = "1.0.0"
authors = [{ name = "Mad Dog Fist" }]
description = "Makes Sting Like a Bee better. Hold down -Disable Lunge- button to deactivate dash."

[tool.sdkmod]
name = "SLAB Qol"
mod_type = "Standard" # or "Library"
supported_games = "BL1"
coop_support = "Unknown"
auto_enable = "False"
license = {name = "GPL3", url = "https://choosealicense.com/licenses/gpl-3.0/" }
